/* The following code was generated by JFlex 1.3.5 on 31/10/2021, 12:10 */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 31/10/2021, 12:10 from the specification file
 * <tt>file:/C:/Users/cipri/eclipse-workspace/TEST/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\45\1\0\1\11"+
    "\5\0\1\46\1\47\1\42\1\40\1\50\1\41\1\14\1\4\12\7"+
    "\1\34\1\51\1\43\1\35\1\44\2\0\32\5\1\0\1\10\2\0"+
    "\1\6\1\0\1\23\1\5\1\33\1\30\1\22\1\31\1\21\1\37"+
    "\1\20\2\5\1\24\1\27\1\13\1\26\1\25\1\5\1\17\1\15"+
    "\1\16\1\32\1\5\1\36\3\5\1\0\1\12\uff83\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    42,    84,    84,   126,   168,   210,   252,   294,   336, 
      378,   420,   462,   504,   546,   588,   630,   672,   714,   756, 
      798,   840,   882,   924,    84,   966,    84,    84,  1008,  1050, 
     1092,    84,    84,    84,    84,  1134,   378,   294,  1176,  1176, 
     1218,  1260,  1302,   210,  1344,  1386,   210,  1428,  1470,  1512, 
     1554,   210,  1596,  1638,   210,  1680,  1722,  1764,    84,  1806, 
     1848,    84,    84,    84,    84,   210,  1890,  1932,  1974,  2016, 
      210,  2058,  2100,   210,  2142,   210,  2184,   210,  2226,  2268, 
     2310,  2352,  2394,  2436,  2478,   210,   210,  2520,  2562,  2604, 
     2646,   210,  2688,   210,  2730,  2772,  2814,  2856,  2898,  2940, 
     2982,  3024,   210,  3066,   210,  3108,  3150,  3192,  3234,   210, 
      210,   210,   210,  3276,  3318,   210,  3360,   210,  3402,  3444, 
     3486,  3528,  3570,  3612,  3654,   210,  3696,    84,  3738,  3780, 
     3822,   210,    84,  3864,  3906,   210,  3948,   210
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\5\1\4\1\6\1\7\1\3\1\10"+
    "\1\3\1\11\1\3\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\7\1\20\1\21\1\7\1\22\1\23\1\24"+
    "\1\25\1\26\1\7\1\27\1\30\1\31\1\32\1\7"+
    "\1\33\1\34\1\35\1\36\1\37\1\4\1\40\1\41"+
    "\1\42\1\43\52\3\53\0\1\4\54\0\1\44\52\0"+
    "\3\7\3\0\1\7\1\0\17\7\2\0\2\7\21\0"+
    "\1\10\4\0\1\45\35\0\10\46\1\47\1\50\2\0"+
    "\2\46\1\0\27\46\2\0\2\46\5\0\3\7\3\0"+
    "\1\7\1\0\11\7\1\51\5\7\2\0\2\7\21\0"+
    "\1\45\47\0\3\7\3\0\1\7\1\0\1\7\1\52"+
    "\3\7\1\53\11\7\2\0\2\7\17\0\3\7\3\0"+
    "\1\7\1\0\11\7\1\54\5\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\5\7\1\55\11\7\2\0"+
    "\2\7\17\0\3\7\3\0\1\56\1\0\14\7\1\57"+
    "\2\7\2\0\2\7\17\0\3\7\3\0\1\60\1\0"+
    "\7\7\1\61\7\7\2\0\2\7\17\0\3\7\3\0"+
    "\1\62\1\0\17\7\2\0\2\7\17\0\3\7\3\0"+
    "\1\7\1\0\2\7\1\63\14\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\2\7\1\64\14\7\2\0"+
    "\2\7\17\0\3\7\3\0\1\7\1\0\11\7\1\65"+
    "\5\7\2\0\2\7\17\0\3\7\3\0\1\7\1\0"+
    "\2\7\1\66\6\7\1\67\5\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\11\7\1\70\3\7\1\71"+
    "\1\7\2\0\2\7\17\0\3\7\3\0\1\7\1\0"+
    "\7\7\1\72\7\7\2\0\2\7\47\0\1\73\21\0"+
    "\3\7\3\0\1\7\1\0\2\7\1\74\14\7\2\0"+
    "\1\7\1\75\54\0\1\76\44\0\1\77\6\0\1\100"+
    "\42\0\1\101\14\0\1\44\1\4\1\5\47\44\10\0"+
    "\1\47\1\50\45\0\3\7\3\0\1\7\1\0\1\7"+
    "\1\102\15\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\2\7\1\103\14\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\7\1\0\1\7\1\104\15\7\2\0\2\7"+
    "\17\0\3\7\3\0\1\7\1\0\1\7\1\105\4\7"+
    "\1\106\10\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\1\7\1\107\15\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\7\1\0\13\7\1\110\3\7\2\0\2\7"+
    "\17\0\3\7\3\0\1\7\1\0\1\111\16\7\2\0"+
    "\2\7\17\0\3\7\3\0\1\7\1\0\13\7\1\112"+
    "\3\7\2\0\2\7\17\0\3\7\3\0\1\7\1\0"+
    "\11\7\1\113\5\7\2\0\2\7\17\0\3\7\3\0"+
    "\1\7\1\0\13\7\1\114\3\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\6\7\1\115\10\7\2\0"+
    "\2\7\17\0\3\7\3\0\1\7\1\0\2\7\1\116"+
    "\14\7\2\0\2\7\17\0\3\7\3\0\1\117\1\0"+
    "\17\7\2\0\2\7\17\0\3\7\3\0\1\7\1\0"+
    "\5\7\1\120\11\7\2\0\2\7\17\0\3\7\3\0"+
    "\1\7\1\0\3\7\1\121\13\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\3\7\1\122\13\7\2\0"+
    "\2\7\17\0\3\7\3\0\1\7\1\0\3\7\1\123"+
    "\13\7\2\0\2\7\17\0\3\7\3\0\1\7\1\0"+
    "\17\7\2\0\2\7\5\0\1\124\11\0\3\7\3\0"+
    "\1\7\1\0\15\7\1\125\1\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\7\7\1\126\3\7\1\127"+
    "\3\7\2\0\2\7\17\0\3\7\3\0\1\7\1\0"+
    "\3\7\1\130\4\7\1\131\2\7\1\132\1\133\2\7"+
    "\2\0\2\7\17\0\3\7\3\0\1\7\1\0\5\7"+
    "\1\134\11\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\4\7\1\135\12\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\7\1\0\17\7\2\0\1\136\1\7\17\0"+
    "\3\7\3\0\1\7\1\0\16\7\1\137\2\0\2\7"+
    "\17\0\3\7\3\0\1\7\1\0\6\7\1\140\10\7"+
    "\2\0\2\7\17\0\3\7\3\0\1\7\1\0\1\7"+
    "\1\141\15\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\7\7\1\142\7\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\143\1\0\17\7\2\0\2\7\36\0\1\144"+
    "\6\0\1\145\23\0\3\7\3\0\1\7\1\0\2\7"+
    "\1\146\14\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\14\7\1\147\2\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\7\1\0\2\7\1\150\14\7\2\0\2\7"+
    "\17\0\3\7\3\0\1\7\1\0\11\7\1\151\5\7"+
    "\2\0\2\7\17\0\3\7\3\0\1\7\1\0\11\7"+
    "\1\152\3\7\1\153\1\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\7\1\0\2\7\1\154\14\7\2\0\2\7"+
    "\17\0\3\7\3\0\1\7\1\0\1\7\1\155\15\7"+
    "\2\0\2\7\17\0\3\7\3\0\1\7\1\0\2\7"+
    "\1\156\14\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\5\7\1\157\11\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\7\1\0\5\7\1\160\11\7\2\0\2\7"+
    "\17\0\3\7\3\0\1\7\1\0\4\7\1\161\12\7"+
    "\2\0\2\7\32\0\1\162\57\0\1\163\30\0\3\7"+
    "\3\0\1\164\1\0\17\7\2\0\2\7\17\0\3\7"+
    "\3\0\1\7\1\0\11\7\1\165\5\7\2\0\2\7"+
    "\17\0\3\7\3\0\1\7\1\0\2\7\1\166\14\7"+
    "\2\0\2\7\17\0\3\7\3\0\1\167\1\0\17\7"+
    "\2\0\2\7\17\0\3\7\3\0\1\7\1\0\6\7"+
    "\1\170\10\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\3\7\1\171\13\7\2\0\2\7\25\0\1\172"+
    "\62\0\1\173\32\0\3\7\3\0\1\7\1\0\4\7"+
    "\1\174\12\7\2\0\2\7\17\0\3\7\3\0\1\7"+
    "\1\0\16\7\1\175\2\0\2\7\17\0\3\7\3\0"+
    "\1\7\1\0\12\7\1\176\4\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\11\7\1\177\5\7\2\0"+
    "\2\7\34\0\1\200\55\0\1\201\30\0\3\7\3\0"+
    "\1\7\1\0\2\7\1\202\14\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\1\7\1\203\15\7\2\0"+
    "\2\7\17\0\3\7\3\0\1\204\1\0\17\7\2\0"+
    "\2\7\31\0\1\205\37\0\3\7\3\0\1\7\1\0"+
    "\6\7\1\206\10\7\2\0\2\7\17\0\3\7\3\0"+
    "\1\7\1\0\3\7\1\207\13\7\2\0\2\7\17\0"+
    "\3\7\3\0\1\7\1\0\12\7\1\210\4\7\2\0"+
    "\2\7\17\0\3\7\3\0\1\7\1\0\11\7\1\211"+
    "\5\7\2\0\2\7\17\0\3\7\3\0\1\212\1\0"+
    "\17\7\2\0\2\7\12\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  9,  9,  1,  1,  1,  9, 
     9,  9,  9,  0,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  9,  9,  9, 
     9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  0,  0,  1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  9, 
     0,  1,  1,  1,  9,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3990];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 116) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 36: 
          { return symbolFactory.newSymbol("FLOATING_POINT_LITERAL", FLOATING_POINT_LITERAL, new Float(yytext().substring(0,yylength()-1))); }
        case 139: break;
        case 6: 
        case 9: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 25: 
        case 40: 
        case 41: 
        case 42: 
        case 44: 
        case 45: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 52: 
        case 53: 
        case 55: 
        case 56: 
        case 57: 
        case 59: 
        case 60: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 71: 
        case 72: 
        case 74: 
        case 76: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 84: 
        case 87: 
        case 88: 
        case 89: 
        case 90: 
        case 92: 
        case 94: 
        case 95: 
        case 96: 
        case 97: 
        case 98: 
        case 101: 
        case 103: 
        case 105: 
        case 106: 
        case 107: 
        case 108: 
        case 116: 
        case 118: 
        case 119: 
        case 120: 
        case 123: 
        case 124: 
        case 126: 
        case 129: 
        case 130: 
        case 133: 
        case 134: 
        case 136: 
          { return symbolFactory.newSymbol("IDENTIFIER", IDENTIFIER, yytext()); }
        case 140: break;
        case 30: 
          { return symbolFactory.newSymbol("GT", GT); }
        case 141: break;
        case 29: 
          { return symbolFactory.newSymbol("LT", LT); }
        case 142: break;
        case 43: 
          { return symbolFactory.newSymbol("TO", TO); }
        case 143: break;
        case 46: 
          { return symbolFactory.newSymbol("IF", IF); }
        case 144: break;
        case 51: 
          { return symbolFactory.newSymbol("OR", OR); }
        case 145: break;
        case 54: 
          { return symbolFactory.newSymbol("DO", DO); }
        case 146: break;
        case 62: 
          { return symbolFactory.newSymbol("LE", LE); }
        case 147: break;
        case 64: 
          { return symbolFactory.newSymbol("GE", GE); }
        case 148: break;
        case 3: 
        case 4: 
          {                                }
        case 149: break;
        case 2: 
        case 8: 
        case 10: 
        case 23: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 150: break;
        case 7: 
          { return symbolFactory.newSymbol("NUM", NUM, Integer.parseInt(yytext())); }
        case 151: break;
        case 127: 
          { return symbolFactory.newSymbol("SETLINE", SETLINE); }
        case 152: break;
        case 125: 
          { return symbolFactory.newSymbol("PROGRAM", PROGRAM); }
        case 153: break;
        case 32: 
          { return symbolFactory.newSymbol("RPARENT", RPARENT); }
        case 154: break;
        case 31: 
          { return symbolFactory.newSymbol("LPARENT", LPARENT); }
        case 155: break;
        case 111: 
          { return symbolFactory.newSymbol("WHILE", WHILE); }
        case 156: break;
        case 110: 
          { return symbolFactory.newSymbol("WRITE", WRITE); }
        case 157: break;
        case 109: 
          { return symbolFactory.newSymbol("CLEAR", CLEAR); }
        case 158: break;
        case 104: 
          { return symbolFactory.newSymbol("ENDDO", ENDDO); }
        case 159: break;
        case 102: 
          { return symbolFactory.newSymbol("ENDIF", ENDIF); }
        case 160: break;
        case 33: 
          { return symbolFactory.newSymbol("COMMA", COMMA); }
        case 161: break;
        case 24: 
          { return symbolFactory.newSymbol("EQUAL", EQUAL); }
        case 162: break;
        case 135: 
          { return symbolFactory.newSymbol("ENDPROGRAM", ENDPROGRAM); }
        case 163: break;
        case 58: 
          { return symbolFactory.newSymbol("ASSIGNMENT", ASSIGNMENT); }
        case 164: break;
        case 39: 
          { return symbolFactory.newSymbol("STR", STR); }
        case 165: break;
        case 5: 
          { return symbolFactory.newSymbol("DIV", DIV); }
        case 166: break;
        case 26: 
          { return symbolFactory.newSymbol("ADD", ADD); }
        case 167: break;
        case 27: 
          { return symbolFactory.newSymbol("SUB", SUB); }
        case 168: break;
        case 61: 
          { return symbolFactory.newSymbol("POW", POW); }
        case 169: break;
        case 65: 
          { return symbolFactory.newSymbol("NOT", NOT); }
        case 170: break;
        case 70: 
          { return symbolFactory.newSymbol("INT",INT); }
        case 171: break;
        case 73: 
          { return symbolFactory.newSymbol("AND", AND); }
        case 172: break;
        case 75: 
          { return symbolFactory.newSymbol("MOD", MOD); }
        case 173: break;
        case 77: 
          { return symbolFactory.newSymbol("FOR", FOR); }
        case 174: break;
        case 132: 
          { return symbolFactory.newSymbol("SETCOLOR", SETCOLOR); }
        case 175: break;
        case 131: 
          { return symbolFactory.newSymbol("FUNCTION", FUNCTION); }
        case 176: break;
        case 137: 
          { return symbolFactory.newSymbol("ENDFUNCTION", ENDFUNCTION); }
        case 177: break;
        case 28: 
          { return symbolFactory.newSymbol("MULT", MULT); }
        case 178: break;
        case 85: 
          { return symbolFactory.newSymbol("REAL",REAL); }
        case 179: break;
        case 86: 
          { return symbolFactory.newSymbol("READ", READ); }
        case 180: break;
        case 91: 
          { return symbolFactory.newSymbol("ELSE", ELSE); }
        case 181: break;
        case 93: 
          { return symbolFactory.newSymbol("DRAW", DRAW); }
        case 182: break;
        case 34: 
          { return symbolFactory.newSymbol("SEMICOLON", SEMICOLON); }
        case 183: break;
        case 117: 
          { return symbolFactory.newSymbol("ENDFOR", ENDFOR); }
        case 184: break;
        case 115: 
          { return symbolFactory.newSymbol("RETURN", RETURN); }
        case 185: break;
        case 112: 
          { return symbolFactory.newSymbol("STRING",STRING); }
        case 186: break;
        case 63: 
          { return symbolFactory.newSymbol("NEQUAL", NEQUAL); }
        case 187: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
