
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPARENT = 50;
  public static final int LPARENT = 49;
  public static final int POW = 32;
  public static final int FUNCTION = 15;
  public static final int MULT = 30;
  public static final int GE = 42;
  public static final int ASSIGNMENT = 17;
  public static final int STR = 55;
  public static final int UMINUS = 5;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int INT = 10;
  public static final int ENDDO = 23;
  public static final int FOR = 24;
  public static final int MINUS = 4;
  public static final int WRITE = 46;
  public static final int RPAREN = 8;
  public static final int DRAW = 45;
  public static final int SEMICOLON = 52;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int LT = 39;
  public static final int ENDFUNCTION = 16;
  public static final int OR = 35;
  public static final int COMMA = 51;
  public static final int SETLINE = 48;
  public static final int DIV = 31;
  public static final int ENDFOR = 26;
  public static final int ENDPROGRAM = 14;
  public static final int NUM = 53;
  public static final int PLUS = 3;
  public static final int IF = 18;
  public static final int LE = 41;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int EQUAL = 37;
  public static final int error = 1;
  public static final int PROGRAM = 13;
  public static final int ADD = 28;
  public static final int NUMBER = 9;
  public static final int MOD = 33;
  public static final int REAL = 11;
  public static final int TIMES = 6;
  public static final int SETCOLOR = 47;
  public static final int ENDIF = 20;
  public static final int FLOATING_POINT_LITERAL = 56;
  public static final int ELSE = 19;
  public static final int READ = 43;
  public static final int TO = 25;
  public static final int WHILE = 21;
  public static final int NEQUAL = 38;
  public static final int CLEAR = 44;
  public static final int STRING = 12;
  public static final int GT = 40;
  public static final int SUB = 29;
  public static final int DO = 22;
  public static final int IDENTIFIER = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "INT",
  "REAL",
  "STRING",
  "PROGRAM",
  "ENDPROGRAM",
  "FUNCTION",
  "ENDFUNCTION",
  "ASSIGNMENT",
  "IF",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDDO",
  "FOR",
  "TO",
  "ENDFOR",
  "RETURN",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "POW",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "EQUAL",
  "NEQUAL",
  "LT",
  "GT",
  "LE",
  "GE",
  "READ",
  "CLEAR",
  "DRAW",
  "WRITE",
  "SETCOLOR",
  "SETLINE",
  "LPARENT",
  "RPARENT",
  "COMMA",
  "SEMICOLON",
  "NUM",
  "IDENTIFIER",
  "STR",
  "FLOATING_POINT_LITERAL"
  };
}

